# -*- coding: utf-8 -*-
"""phase1_ml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dO13IoopNCEjXzMQXB-kyjC-DARuQSde
"""

import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

data = pd.read_csv("/content/drive/MyDrive/Sample Data for colab/application_train.csv/application_train.csv")

data.head()



print(data.shape)
print(f"Total rows: {data.shape[0]}, Total columns: {data.shape[1]}")

data.info()

print(data["TARGET"].value_counts())
print("\nPercentage:")
print(data["TARGET"].value_counts(normalize=True) * 100)

missing = data.isnull().sum().sort_values(ascending=False)

missing_df = pd.DataFrame({
    "missing_count": missing,
    "missing_percent": (missing / len(data)) * 100
})

missing_df

print(data.dtypes.value_counts())

unique_counts = data.nunique().sort_values()
unique_counts

print("Duplicate rows:", data.duplicated().sum())

# 1. Target distribution
print("TARGET distribution:")
print(data["TARGET"].value_counts())

print("\nTARGET percentage:")
print(data["TARGET"].value_counts(normalize=True) * 100)


# 2. Missing values
missing = data.isnull().sum().sort_values(ascending=False)

missing_df = pd.DataFrame({
    "missing_count": missing,
    "missing_percent": (missing / len(data)) * 100
})

print("\nTop 20 columns by missing values:")
display(missing_df.head(20))


# 3. Data types
print("\nData types:")
print(data.dtypes.value_counts())


# 4. Unique values
print("\nLowest unique-value columns:")
print(data.nunique().sort_values().head(20))


# 5. Duplicate rows
print("\nDuplicate rows:", data.duplicated().sum())

X = data.drop(columns=["TARGET", "SK_ID_CURR"])
y = data["TARGET"]

categorical_cols = X.select_dtypes(include=["object"]).columns.tolist()
numeric_cols = X.select_dtypes(exclude=["object"]).columns.tolist()

print("Categorical:", len(categorical_cols))
print("Numeric:", len(numeric_cols))

data["CREDIT_INCOME_RATIO"] = (
    data["AMT_CREDIT"] / data["AMT_INCOME_TOTAL"]
)

data["ANNUITY_INCOME_RATIO"] = (
    data["AMT_ANNUITY"] / data["AMT_INCOME_TOTAL"]
)

data["CREDIT_ANNUITY_RATIO"] = (
    data["AMT_CREDIT"] / data["AMT_ANNUITY"]
)

data["INCOME_PER_CHILD"] = (
    data["AMT_INCOME_TOTAL"] / (data["CNT_CHILDREN"] + 1)
)

from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

print("Shape:", data.shape)

print("\nCategorical columns:")
print(data.select_dtypes(include="object").columns.tolist())

print("\nNumeric columns:", len(data.select_dtypes(exclude="object").columns))

print("\nColumns with >50% missing:")
high_missing = (
    data.isnull().mean()
    .sort_values(ascending=False)
)

print(high_missing[high_missing > 0.50])

categorical_cols = X_train.select_dtypes(include=["object"]).columns.tolist()

for col in categorical_cols:
    X_train[col] = X_train[col].astype("category")
    X_valid[col] = X_valid[col].astype("category")

print("Categorical features:", len(categorical_cols))

import lightgbm as lgb

model = lgb.LGBMClassifier(
    objective="binary",
    n_estimators=1000,
    learning_rate=0.03,
    num_leaves=31,
    max_depth=-1,
    subsample=0.8,
    colsample_bytree=0.8,
    reg_alpha=0.1,
    reg_lambda=0.1,
    random_state=42,
    n_jobs=-1
)

model.fit(
    X_train,
    y_train,
    categorical_feature=categorical_cols,
    eval_set=[(X_valid, y_valid)],
    callbacks=[
        lgb.early_stopping(50),
        lgb.log_evaluation(100)
    ]
)

from sklearn.metrics import (
    roc_auc_score,
    average_precision_score,
    confusion_matrix,
    classification_report
)

y_prob = model.predict_proba(X_valid)[:, 1]

roc_auc = roc_auc_score(y_valid, y_prob)
pr_auc = average_precision_score(y_valid, y_prob)

print("ROC-AUC:", roc_auc)
print("PR-AUC:", pr_auc)

gini = 2 * roc_auc - 1

print("Gini:", gini)

from sklearn.metrics import roc_curve

fpr, tpr, thresholds = roc_curve(y_valid, y_prob)

ks = np.max(tpr - fpr)

print("KS:", ks)

importance_df = pd.DataFrame({
    "feature": X_train.columns,
    "importance_gain": model.booster_.feature_importance(
        importance_type="gain"
    )
})

importance_df = importance_df.sort_values(
    "importance_gain",
    ascending=False
)

importance_df.head(30)

import shap

explainer = shap.TreeExplainer(model)

X_shap = X_valid.sample(
    min(10000, len(X_valid)),
    random_state=42
)

shap_values = explainer.shap_values(X_shap)

if isinstance(shap_values, list):
    shap_values_for_class_1 = shap_values[1]
else:
    shap_values_for_class_1 = shap_values

shap_importance = pd.DataFrame({
    "feature": X_shap.columns,
    "mean_abs_shap": np.abs(
        shap_values_for_class_1
    ).mean(axis=0)
})

shap_importance = shap_importance.sort_values(
    "mean_abs_shap",
    ascending=False
)

shap_importance.head(30)

low_importance_features = shap_importance[
    shap_importance["mean_abs_shap"] < 0.0005
]["feature"].tolist()

print("Candidates for removal:", len(low_importance_features))

X_train_reduced = X_train.drop(
    columns=low_importance_features
)

X_valid_reduced = X_valid.drop(
    columns=low_importance_features
)

model_reduced = lgb.LGBMClassifier(
    objective="binary",
    n_estimators=1000,
    learning_rate=0.03,
    num_leaves=31,
    max_depth=-1,
    subsample=0.8,
    colsample_bytree=0.8,
    reg_alpha=0.1,
    reg_lambda=0.1,
    random_state=42,
    n_jobs=-1
)

model_reduced.fit(
    X_train_reduced,
    y_train,
    categorical_feature=[
        c for c in categorical_cols
        if c in X_train_reduced.columns
    ],
    eval_set=[(X_valid_reduced, y_valid)],
    callbacks=[
        lgb.early_stopping(50),
        lgb.log_evaluation(100)
    ]
)

y_prob_reduced = model_reduced.predict_proba(
    X_valid_reduced
)[:, 1]

roc_auc_reduced = roc_auc_score(
    y_valid,
    y_prob_reduced
)

gini_reduced = 2 * roc_auc_reduced - 1

fpr, tpr, _ = roc_curve(y_valid, y_prob_reduced)
ks_reduced = np.max(tpr - fpr)

print("Original ROC-AUC:", roc_auc)
print("Reduced ROC-AUC:", roc_auc_reduced)

print("Original Gini:", gini)
print("Reduced Gini:", gini_reduced)

print("Original KS:", ks)
print("Reduced KS:", ks_reduced)

!git config --global user.name "https://github.com/harshraj1706"
!git config --global user.email "harshraj17060@gmail.com"

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/AegisFin-AI

!cp "/content/drive/MyDrive/Colab Notebooks/phase1_ml.ipynb" "/content/AegisFin-AI/phase1_ml.ipynb"

!ls

!git status

!git add phase1_ml.ipynb

!git status

!git commit -m "Add phase 1 ML notebook"

!git push origin main

